{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vdocipher.aegis",
    "module": "vdocipher-android",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vdocipher-android-1.12.1.aar",
          "url": "vdocipher-android-1.12.1.aar",
          "size": 294740,
          "sha512": "9e95159542a349521d391be088885890bc1fb44884d18258e4bab457732251ff7255291fb01c2d745545fd7e51e35e2598dd70033c50332b2756960c51642a3d",
          "sha256": "3cc4d9a0d7d415342d5ef319848f23caf2c34ad3c7562b3a0c2ac87d7d88f5bb",
          "sha1": "b3e861adda5e6bc847537055440be9eab580b633",
          "md5": "2567641a62ac5250d644371e123fca86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.12.1.aar",
          "url": "vdocipher-android-1.12.1.aar",
          "size": 294740,
          "sha512": "9e95159542a349521d391be088885890bc1fb44884d18258e4bab457732251ff7255291fb01c2d745545fd7e51e35e2598dd70033c50332b2756960c51642a3d",
          "sha256": "3cc4d9a0d7d415342d5ef319848f23caf2c34ad3c7562b3a0c2ac87d7d88f5bb",
          "sha1": "b3e861adda5e6bc847537055440be9eab580b633",
          "md5": "2567641a62ac5250d644371e123fca86"
        }
      ]
    }
  ]
}
