{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vdocipher.aegis",
    "module": "vdocipher-android",
    "version": "1.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.24.1.aar",
          "url": "vdocipher-android-1.24.1.aar",
          "size": 872848,
          "sha512": "096e3f92328dc61a271914f74afe09597009d8b20f045b7a3075384bf44454ff7ec8775b5c08c95f6d14483b428bab8614acfa0a447f1a269beb2f2e4c1a4d52",
          "sha256": "f1267db8377f06a6527fcd1835d4d5a9ca71fa3b86715ee0dadcc5971aee37a3",
          "sha1": "fc38f7fe6fd55c1b0d00bf247d1b2f1cd5c5d6e3",
          "md5": "67679bc675bbe23a385f6e1f7f237aa0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.24.1.aar",
          "url": "vdocipher-android-1.24.1.aar",
          "size": 872848,
          "sha512": "096e3f92328dc61a271914f74afe09597009d8b20f045b7a3075384bf44454ff7ec8775b5c08c95f6d14483b428bab8614acfa0a447f1a269beb2f2e4c1a4d52",
          "sha256": "f1267db8377f06a6527fcd1835d4d5a9ca71fa3b86715ee0dadcc5971aee37a3",
          "sha1": "fc38f7fe6fd55c1b0d00bf247d1b2f1cd5c5d6e3",
          "md5": "67679bc675bbe23a385f6e1f7f237aa0"
        }
      ]
    }
  ]
}
