{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vdocipher.aegis",
    "module": "vdocipher-android",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.21.1.aar",
          "url": "vdocipher-android-1.21.1.aar",
          "size": 865864,
          "sha512": "4d7ad406be023a87c87752515a12e8dd01bd5d4a2e18dd3a362644286e9ce50d150bde3005bf3e42d203185407e46c592fe972b0a9cee5b86d20301c85393a87",
          "sha256": "e14d39eff86f4d2580ae5cc1b8543880e31b3ac82f0e6e1fc1f86c64e6c8381d",
          "sha1": "46f7899e32b2884cec6c65598fae0bbda90a80d8",
          "md5": "8e60aa2074d6ffc8e8dbcab742e24a5d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.21.1.aar",
          "url": "vdocipher-android-1.21.1.aar",
          "size": 865864,
          "sha512": "4d7ad406be023a87c87752515a12e8dd01bd5d4a2e18dd3a362644286e9ce50d150bde3005bf3e42d203185407e46c592fe972b0a9cee5b86d20301c85393a87",
          "sha256": "e14d39eff86f4d2580ae5cc1b8543880e31b3ac82f0e6e1fc1f86c64e6c8381d",
          "sha1": "46f7899e32b2884cec6c65598fae0bbda90a80d8",
          "md5": "8e60aa2074d6ffc8e8dbcab742e24a5d"
        }
      ]
    }
  ]
}
