{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vdocipher.aegis",
    "module": "vdocipher-android",
    "version": "1.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.5.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.27.0.aar",
          "url": "vdocipher-android-1.27.0.aar",
          "size": 1825600,
          "sha512": "7275212a490de6d7332e287dd3459943fc42aace36a18f87e47b0194778af80954f0dddc73da23addecb59e223b6e0406d7f3cac0052a450b0e36c4eb5a5aaa8",
          "sha256": "97cc6e6bf431ed8d463fc142e9828dbae3705c524b193f78ed57b3adf454e37e",
          "sha1": "96e37c46439edda2aa577565d6a5d8652dddd1de",
          "md5": "896735b94a7f4102316be2917ca09c97"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.5.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.27.0.aar",
          "url": "vdocipher-android-1.27.0.aar",
          "size": 1825600,
          "sha512": "7275212a490de6d7332e287dd3459943fc42aace36a18f87e47b0194778af80954f0dddc73da23addecb59e223b6e0406d7f3cac0052a450b0e36c4eb5a5aaa8",
          "sha256": "97cc6e6bf431ed8d463fc142e9828dbae3705c524b193f78ed57b3adf454e37e",
          "sha1": "96e37c46439edda2aa577565d6a5d8652dddd1de",
          "md5": "896735b94a7f4102316be2917ca09c97"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "vdocipher-android-1.27.0-sources.jar",
          "url": "vdocipher-android-1.27.0-sources.jar",
          "size": 730243,
          "sha512": "471e9f01d8c6c4bedbe6f3e063a87d4696ce9dd8ce1b1f518331513b37cc4144372c2eb4c8800707ecda03cad70b6e19300c161303bbc3b3443d32c761192f2a",
          "sha256": "8d65889bfe9a56d4ee57fe2e201ba3c8ef203fb0bfba9677299f51358e16341c",
          "sha1": "3f6e5b0f90d3b944bb621eef2007b5b21ddaa651",
          "md5": "d8d49edf0be7d2e221f404b1ec27b94e"
        }
      ]
    }
  ]
}
