{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vdocipher.aegis",
    "module": "vdocipher-android",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vdocipher-android-1.12.0.aar",
          "url": "vdocipher-android-1.12.0.aar",
          "size": 294811,
          "sha512": "d77fe771a000b005ae0c24eabe1f9ef9cf024e93fa4a0ec6007af39a10d3147e1c00a76a40ccae5a93347ad423ba874882d3943df139dc0fd07df0f4bff8fa2b",
          "sha256": "96b7da0a30e34f524fb14c6267a95864cbbef29d732addcc80c8a0bc9e6ea51c",
          "sha1": "3338a24d8c7bd2de219d9472bee106eecd20b7f1",
          "md5": "7792e47bcc6f570c903b6a800e49140f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.12.0.aar",
          "url": "vdocipher-android-1.12.0.aar",
          "size": 294811,
          "sha512": "d77fe771a000b005ae0c24eabe1f9ef9cf024e93fa4a0ec6007af39a10d3147e1c00a76a40ccae5a93347ad423ba874882d3943df139dc0fd07df0f4bff8fa2b",
          "sha256": "96b7da0a30e34f524fb14c6267a95864cbbef29d732addcc80c8a0bc9e6ea51c",
          "sha1": "3338a24d8c7bd2de219d9472bee106eecd20b7f1",
          "md5": "7792e47bcc6f570c903b6a800e49140f"
        }
      ]
    }
  ]
}
