{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vdocipher.aegis",
    "module": "vdocipher-android",
    "version": "1.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "acwfwyrka5hs5mbaq7pgl3xgjq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vdocipher-android-1.10.1.aar",
          "url": "vdocipher-android-1.10.1.aar",
          "size": 242653,
          "sha512": "1672b99edacdc459e34836f27bf4014806962a58a0eaeb238fa8e9b9c7759c289ebb1d97e7c3e76abcd7b443bea3103e7c80472cb41063d26d75fe8c4a0a3995",
          "sha256": "f950db897bc08714d7de7a6bb24296cab76d5cd27d8a07fddfd8e020c3c0b50d",
          "sha1": "54eb0c7815153f93af470ac53277f813ec599384",
          "md5": "f402da18cf15817d113e24c28c08c369"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.10.1.aar",
          "url": "vdocipher-android-1.10.1.aar",
          "size": 242653,
          "sha512": "1672b99edacdc459e34836f27bf4014806962a58a0eaeb238fa8e9b9c7759c289ebb1d97e7c3e76abcd7b443bea3103e7c80472cb41063d26d75fe8c4a0a3995",
          "sha256": "f950db897bc08714d7de7a6bb24296cab76d5cd27d8a07fddfd8e020c3c0b50d",
          "sha1": "54eb0c7815153f93af470ac53277f813ec599384",
          "md5": "f402da18cf15817d113e24c28c08c369"
        }
      ]
    }
  ]
}
