{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vdocipher.aegis",
    "module": "vdocipher-android",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vdocipher-android-1.11.0.aar",
          "url": "vdocipher-android-1.11.0.aar",
          "size": 289182,
          "sha512": "3b26812678c7eea41b31a441ac315cc7ee398fe08b8aad2f0e5185282dabd6db5418d455bc8a80777131607706ed257db620d3b1e3a17e0e48603022fcfce389",
          "sha256": "5d5966ae0d64f1852bcffe63ee811d5bd5f061a24bb3577448ce53486bb0534c",
          "sha1": "9f1baa0aec84390a0bd151a5475ad6bccf7d94ab",
          "md5": "276c127559be105fcca20bf694c4b853"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.11.0.aar",
          "url": "vdocipher-android-1.11.0.aar",
          "size": 289182,
          "sha512": "3b26812678c7eea41b31a441ac315cc7ee398fe08b8aad2f0e5185282dabd6db5418d455bc8a80777131607706ed257db620d3b1e3a17e0e48603022fcfce389",
          "sha256": "5d5966ae0d64f1852bcffe63ee811d5bd5f061a24bb3577448ce53486bb0534c",
          "sha1": "9f1baa0aec84390a0bd151a5475ad6bccf7d94ab",
          "md5": "276c127559be105fcca20bf694c4b853"
        }
      ]
    }
  ]
}
