{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vdocipher.aegis",
    "module": "vdocipher-android",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ekvgushr75exnctjfxlvkccgf4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vdocipher-android-1.10.0.aar",
          "url": "vdocipher-android-1.10.0.aar",
          "size": 405743,
          "sha512": "60c07d3da406d96d54331905a0514ac4a9b71bcacad3aea6f4782397a240328a613b8866ad44a2136cff440c3ff2dac8307755ec2f9a01e4271013fab98132e1",
          "sha256": "eaea8fbb6868b07b16646f0c0a5d8071f0d3abc5885a4cba2702539d435c439f",
          "sha1": "0075ee2a0ac0b16213113b6d783afda21ffdb2dd",
          "md5": "4af1e36b59032a324ed82d18095ffe8f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "com.loopj.android",
          "module": "android-async-http",
          "version": {
            "requires": "1.4.9"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.10.0.aar",
          "url": "vdocipher-android-1.10.0.aar",
          "size": 405743,
          "sha512": "60c07d3da406d96d54331905a0514ac4a9b71bcacad3aea6f4782397a240328a613b8866ad44a2136cff440c3ff2dac8307755ec2f9a01e4271013fab98132e1",
          "sha256": "eaea8fbb6868b07b16646f0c0a5d8071f0d3abc5885a4cba2702539d435c439f",
          "sha1": "0075ee2a0ac0b16213113b6d783afda21ffdb2dd",
          "md5": "4af1e36b59032a324ed82d18095ffe8f"
        }
      ]
    }
  ]
}
