{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vdocipher.aegis",
    "module": "vdocipher-android",
    "version": "1.22.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.22.5.aar",
          "url": "vdocipher-android-1.22.5.aar",
          "size": 867245,
          "sha512": "9d4f3ee995e227ef7abc67a8d1459a6c08c7626bf88765d504375a0d4342a408ad8db69135b78eda057b3e37c7026cff39d124d780202b41f23495caa8bc91dd",
          "sha256": "e19bb01c3d7e3c71112302a4202112a8b1a45217bb7f48d6cd1e2a2aef87e69a",
          "sha1": "36ae049f3fb16db84eea6677b0a59628b7cb97e8",
          "md5": "6c696244857bf1b148a807d7ac96dc3d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vdocipher-android-1.22.5.aar",
          "url": "vdocipher-android-1.22.5.aar",
          "size": 867245,
          "sha512": "9d4f3ee995e227ef7abc67a8d1459a6c08c7626bf88765d504375a0d4342a408ad8db69135b78eda057b3e37c7026cff39d124d780202b41f23495caa8bc91dd",
          "sha256": "e19bb01c3d7e3c71112302a4202112a8b1a45217bb7f48d6cd1e2a2aef87e69a",
          "sha1": "36ae049f3fb16db84eea6677b0a59628b7cb97e8",
          "md5": "6c696244857bf1b148a807d7ac96dc3d"
        }
      ]
    }
  ]
}
